from pathlib import Path

src = Path('scripts/recortar_fatec_visuais.py').read_text(encoding='utf-8')
old = '''    if not comps:\n        return None\n    area, x, y, w, h = max(comps)\n    pad = 10\n    x0 = max(0, x - pad); y0 = max(0, y - pad)\n    x1 = min(mask.shape[1], x + w + pad); y1 = min(mask.shape[0], y + h + pad)\n    return fitz.Rect(region.x0 + x0 / scale, region.y0 + y0 / scale,\n                     region.x0 + x1 / scale, region.y0 + y1 / scale)\n'''
new = '''    if not comps:\n        # Diagramas/tabelas vetoriais podem ser formados por muitos traços pequenos.\n        # Faz uma segunda passagem menos restritiva e une os componentes úteis.\n        comps2 = []\n        for lab in range(1, n):\n            x, y, w, h, area = stats[lab]\n            if area < 35 or w < 4 or h < 4:\n                continue\n            if (w > .90 * mask.shape[1] and h < 22) or (h > .90 * mask.shape[0] and w < 10):\n                continue\n            comps2.append((area, x, y, w, h))\n        comps = comps2\n    if not comps:\n        return None\n\n    # Em vez de guardar apenas o maior componente, une componentes próximos.\n    # Isso captura tabelas, eixos, circuitos e diagramas sem reintroduzir o texto mascarado.\n    seed = max(comps, key=lambda c: c[0])\n    _, sx, sy, sw, sh = seed\n    ux0, uy0, ux1, uy1 = sx, sy, sx + sw, sy + sh\n    changed = True\n    while changed:\n        changed = False\n        for area, x, y, w, h in comps:\n            cx0, cy0, cx1, cy1 = x, y, x + w, y + h\n            gapx = max(0, max(ux0, cx0) - min(ux1, cx1))\n            gapy = max(0, max(uy0, cy0) - min(uy1, cy1))\n            # tolerância maior na vertical para rótulos/partes de um mesmo gráfico\n            if gapx <= 55 and gapy <= 70:\n                nx0, ny0 = min(ux0, cx0), min(uy0, cy0)\n                nx1, ny1 = max(ux1, cx1), max(uy1, cy1)\n                if (nx0, ny0, nx1, ny1) != (ux0, uy0, ux1, uy1):\n                    ux0, uy0, ux1, uy1 = nx0, ny0, nx1, ny1\n                    changed = True\n    pad = 12\n    x0 = max(0, ux0 - pad); y0 = max(0, uy0 - pad)\n    x1 = min(mask.shape[1], ux1 + pad); y1 = min(mask.shape[0], uy1 + pad)\n    return fitz.Rect(region.x0 + x0 / scale, region.y0 + y0 / scale,\n                     region.x0 + x1 / scale, region.y0 + y1 / scale)\n'''
if old not in src:
    raise RuntimeError('Trecho-base do detector não encontrado')
src = src.replace(old, new)
# A execução deve continuar mesmo se alguns candidatos forem falsos positivos; o relatório é impresso.
src = src.replace("if failed:\n    print('FALHAS:', failed)\n    raise SystemExit(2)\n", "if failed:\n    print('FALHAS_RESTANTES:', failed)\n")
exec(compile(src, 'recortar_fatec_visuais_v2_runtime.py', 'exec'))
